server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /portal/niceair/ {
    proxy_pass https://niceair.paperlessfbo.com/;
    proxy_ssl_server_name on;
    proxy_set_header Host niceair.paperlessfbo.com;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect / /portal/niceair/;
    proxy_redirect https://niceair.paperlessfbo.com/ /portal/niceair/;
    proxy_cookie_path / /portal/niceair/;
    proxy_buffering off;
  }

  location /portal/squadron2/ {
    proxy_pass https://scheduler.squadron2.com/;
    proxy_ssl_server_name on;
    proxy_set_header Host scheduler.squadron2.com;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect / /portal/squadron2/;
    proxy_redirect https://scheduler.squadron2.com/ /portal/squadron2/;
    proxy_cookie_path / /portal/squadron2/;
    proxy_buffering off;
  }

  location /portal/advantage/ {
    proxy_pass https://advantage.paperlessfbo.com/;
    proxy_ssl_server_name on;
    proxy_set_header Host advantage.paperlessfbo.com;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect / /portal/advantage/;
    proxy_redirect https://advantage.paperlessfbo.com/ /portal/advantage/;
    proxy_cookie_path / /portal/advantage/;
    proxy_buffering off;
  }
}
